export const START_DOWNLOAD_CRYPTOCURRENCIES = 'START_DOWNLOAD_CRYPTOCURRENCIES';
export const DOWNLOAD_CRYPTOCURRENCIES_SUCCESS = 'DOWNLOAD_CRYPTOCURRENCIES_SUCCESS';
export const DOWNLOAD_CRYPTOCURRENCIES_ERROR = 'DOWNLOAD_CRYPTOCURRENCIES_ERROR';

export const START_DOWNLOAD_CRYPTOCURRENCY_PRICE = 'START_DOWNLOAD_CRYPTOCURRENCY_PRICE';
export const DOWNLOAD_CRYPTOCURRENCY_PRICE_SUCCESS = 'DOWNLOAD_CRYPTOCURRENCY_PRICE_SUCCESS';
export const DOWNLOAD_CRYPTOCURRENCY_PRICE_ERROR = 'DOWNLOAD_CRYPTOCURRENCY_PRICE_ERROR';
