export const START_DOWNLOAD_CRYPTOCURRENCIES = 'START_DOWNLOAD_CRYPTOCURRENCIES';
export const DOWNLOAD_CRYPTOCURRENCIES_SUCCESS = 'DOWNLOAD_CRYPTOCURRENCIES_SUCCESS';
export const DOWNLOAD_CRYPTOCURRENCIES_ERROR = 'DOWNLOAD_CRYPTOCURRENCIES_ERROR';
